<?php

/**
 * PluginmyPageMetaTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmyPageMetaTable extends myBaseTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmyPageMetaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmyPageMeta');
    }


    public function getByUrl($url)
    {
        return $this->createQuery('a')
            ->where('a.url = ?', $url)
            ->fetchOne();
    }
}