
# Мета-теги страницы
# ==========================================================
myPageMeta:
  tableName:  my_page_metas
  columns:
    url:                      { type: string(255), notnull: true, unique: true }
    meta_title:               { type: string(255) }
    meta_description:         { type: string }
    meta_keywords:            { type: string }
  options:
    type: INNODB
    charset: utf8
